name: Deploy Quartz site to GitHub Pages
on:
  push:
    branches:
      - v4
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Quartz
        uses: jackyzha0/quartz-github-action@v4
        with:
          required_environments: 'true'
